/**
 * Generated by `npm run client:build` from `docs/detection/detectors.md`, `docs/detection/correlation.md`, `docs/policy/actions.md`. Do not edit.
 *
 * The Reference screen's text. See scripts/build-reference.mjs.
 */

/* eslint-disable */
import type { ReferenceData } from "./reference-model.js";

export const REFERENCE: ReferenceData = {
 "intro": {
  "detector": [
   {
    "kind": "p",
    "text": [
     [
      "t",
      "Every detector returns "
     ],
     [
      "b",
      "evidence"
     ],
     [
      "t",
      ", never a verdict. What each one is allowed to conclude is as important as what it looks at, so every entry below names its ceiling."
     ]
    ]
   },
   {
    "kind": "list",
    "items": [
     [
      [
       "b",
       "cost"
      ],
      [
       "t",
       " — "
      ],
      [
       "code",
       "cheap"
      ],
      [
       "t",
       " is synchronous and in-memory; "
      ],
      [
       "code",
       "io"
      ],
      [
       "t",
       " may make a network call."
      ]
     ],
     [
      [
       "b",
       "stage"
      ],
      [
       "t",
       " — "
      ],
      [
       "code",
       "always"
      ],
      [
       "t",
       " runs on every request; "
      ],
      [
       "code",
       "confirming"
      ],
      [
       "t",
       " runs only when a signature matched, because there is nothing to confirm otherwise."
      ]
     ],
     [
      [
       "b",
       "ceiling"
      ],
      [
       "t",
       " — the highest certainty this detector can produce. Only "
      ],
      [
       "code",
       "certain"
      ],
      [
       "t",
       " can cost somebody their access; see the guard."
      ]
     ]
    ]
   },
   {
    "kind": "code",
    "lang": "ts",
    "code": "import { defaultDetectors } from \"@osqd/bothandlerjs\";\n\nnew BotHandler({ detectors: defaultDetectors() });        // the default set\nnew BotHandler({ extraDetectors: [myDetector()] });       // add to it"
   },
   {
    "kind": "p",
    "text": [
     [
      "code",
      "bothandlerjs detectors --preset protect-content"
     ],
     [
      "t",
      " lists what a configuration actually installs, which is the reliable answer for your setup."
     ]
    ]
   }
  ],
  "action": [
   {
    "kind": "p",
    "text": [
     [
      "t",
      "That ordering is the useful one. Every action here will eventually be applied to somebody it should not have been applied to, so the question that matters is what that costs them."
     ]
    ]
   },
   {
    "kind": "table",
    "head": [
     [
      [
       "t",
       "Action"
      ]
     ],
     [
      [
       "t",
       "Terminal"
      ]
     ],
     [
      [
       "t",
       "Costs a person"
      ]
     ]
    ],
    "rows": [
     [
      [
       [
        "code",
        "allow"
       ]
      ],
      [],
      [
       [
        "t",
        "nothing"
       ]
      ]
     ],
     [
      [
       [
        "code",
        "log"
       ]
      ],
      [],
      [
       [
        "t",
        "nothing"
       ]
      ]
     ],
     [
      [
       [
        "code",
        "tag"
       ]
      ],
      [],
      [
       [
        "t",
        "nothing"
       ]
      ]
     ],
     [
      [
       [
        "code",
        "delay"
       ]
      ],
      [],
      [
       [
        "t",
        "a moment"
       ]
      ]
     ],
     [
      [
       [
        "code",
        "rate-limit"
       ]
      ],
      [],
      [
       [
        "t",
        "a retry, if they are fast"
       ]
      ]
     ],
     [
      [
       [
        "code",
        "challenge"
       ]
      ],
      [],
      [
       [
        "t",
        "seconds, and a working browser"
       ]
      ]
     ],
     [
      [
       [
        "code",
        "custom"
       ]
      ],
      [],
      [
       [
        "t",
        "whatever you wrote"
       ]
      ]
     ],
     [
      [
       [
        "code",
        "redirect"
       ]
      ],
      [
       [
        "t",
        "✓"
       ]
      ],
      [
       [
        "t",
        "their destination"
       ]
      ]
     ],
     [
      [
       [
        "code",
        "block"
       ]
      ],
      [
       [
        "t",
        "✓"
       ]
      ],
      [
       [
        "t",
        "the page"
       ]
      ]
     ],
     [
      [
       [
        "code",
        "drop"
       ]
      ],
      [
       [
        "t",
        "✓"
       ]
      ],
      [
       [
        "t",
        "the page, with no explanation"
       ]
      ]
     ]
    ]
   },
   {
    "kind": "p",
    "text": [
     [
      "t",
      "The three marked terminal are the ones the guard will not let rest on a guess."
     ]
    ]
   },
   {
    "kind": "p",
    "text": [
     [
      "t",
      "The engine never touches a response object. It returns an "
     ],
     [
      "code",
      "ActionOutcome"
     ],
     [
      "t",
      " and the adapter applies it — which is why the same policy works identically on Express, Fastify, Koa and a Fetch runtime."
     ]
    ]
   }
  ]
 },
 "entries": [
  {
   "kind": "detector",
   "id": "self-identified",
   "group": "Single-request detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling certain"
   ],
   "summary": "The client told us what it is. This is the backbone of the proven tier.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "The client told us what it is. This is the backbone of the proven tier."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "When a request arrives saying "
      ],
      [
       "code",
       "python-requests/2.31.0"
      ],
      [
       "t",
       " or "
      ],
      [
       "code",
       "Googlebot/2.1"
      ],
      [
       "t",
       ", nothing is being "
      ],
      [
       "i",
       "inferred"
      ],
      [
       "t",
       ". We are taking the client at its word — and if that word is a lie, the misclassification belongs to whoever lied, not to a heuristic that guessed wrong about a person. That is a point about responsibility rather than about technology, and it is why this tier can do what the others may not."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "What it recognises: the signature database (search crawlers, AI crawlers, monitors, scanners, social unfurlers), bare library tokens ("
      ],
      [
       "code",
       "curl/"
      ],
      [
       "t",
       ", "
      ],
      [
       "code",
       "okhttp"
      ],
      [
       "t",
       ", "
      ],
      [
       "code",
       "Go-http-client"
      ],
      [
       "t",
       "), and User-Agents that announce automation outright."
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "ts",
     "code": "// curl/8.4.0\n{ certainty: \"certain\", summary: \"User-Agent identifies curl\",\n  deterministicBasis: 'The product token \"curl/\" is emitted by an HTTP library or an ' +\n    \"automation runtime and by no browser. Nothing a person does in a browser produces it.\" }"
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "A bare token with no browser preamble is "
      ],
      [
       "code",
       "strong"
      ],
      [
       "t",
       " rather than "
      ],
      [
       "code",
       "certain"
      ],
      [
       "t",
       " when it could plausibly be a person's own script; the database's own entries are "
      ],
      [
       "code",
       "certain"
      ],
      [
       "t",
       "."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "ua-coherence",
   "group": "Single-request detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling strong"
   ],
   "summary": "Does this User-Agent contradict itself?",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Does this User-Agent contradict "
      ],
      [
       "i",
       "itself"
      ],
      [
       "t",
       "?"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Every other single-request check compares the User-Agent against something else — the Client Hints, the header set, the header order. This one needs nothing but the string, which makes it the only consistency check that still works on a source with no headers at all: an nginx access line, a CDN log, a WAF event. That is not a small thing when a replay is the main way people evaluate a policy."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "It reads engines, platforms and versions against each other: a Safari token on Windows, a Chrome version that does not exist, a mobile token with a desktop platform."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "header-integrity",
   "group": "Single-request detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling certain"
   ],
   "summary": "Compares the header set against what the client it claims to be would actually send.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Compares the header set against what the client it claims to be would actually send."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "The "
      ],
      [
       "code",
       "certain"
      ],
      [
       "t",
       " cases here are "
      ],
      [
       "b",
       "protocol violations"
      ],
      [
       "t",
       " rather than absences: two "
      ],
      [
       "code",
       "Host"
      ],
      [
       "t",
       " headers, a second "
      ],
      [
       "code",
       "Content-Length"
      ],
      [
       "t",
       ", a connection-specific header on HTTP/2. RFC 9112 requires a recipient to reject those; no compliant client emits them."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Everything else — a browser claim with no "
      ],
      [
       "code",
       "Accept"
      ],
      [
       "t",
       ", no "
      ],
      [
       "code",
       "Accept-Language"
      ],
      [
       "t",
       ", no "
      ],
      [
       "code",
       "Accept-Encoding"
      ],
      [
       "t",
       " — is "
      ],
      [
       "code",
       "moderate"
      ],
      [
       "t",
       " or "
      ],
      [
       "code",
       "strong"
      ],
      [
       "t",
       " and shares a "
      ],
      [
       "b",
       "family"
      ],
      [
       "t",
       ", because a client missing three browser headers has one property reported three times. See families."
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "ts",
     "code": "headerIntegrityDetector({ requireAcceptLanguage: false })   // for an API-only origin"
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "header-order",
   "group": "Single-request detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling moderate"
   ],
   "summary": "The order headers arrived in, against orderings every mainstream browser respects.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "The order headers arrived in, against orderings every mainstream browser respects."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Header order is a fingerprint that a scraper copying your browser's headers usually gets wrong, because it sets them from a dictionary. The rules are stated as invariants — \""
      ],
      [
       "code",
       "X"
      ],
      [
       "t",
       " must not appear after "
      ],
      [
       "code",
       "Y"
      ],
      [
       "t",
       "\" — verified against Chrome, Firefox, Safari and Edge, and kept deliberately few. The value is in rules that no browser breaks; modelling any browser's exact sequence would turn this into a source of false positives on next month's release."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Needs "
      ],
      [
       "code",
       "rawHeaders"
      ],
      [
       "t",
       "; see adapters."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "client-hints",
   "group": "Single-request detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling certain"
   ],
   "summary": "Cross-checks Sec-CH-UA against the legacy User-Agent string.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Cross-checks "
      ],
      [
       "code",
       "Sec-CH-UA"
      ],
      [
       "t",
       " against the legacy User-Agent string."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "A real Chromium generates both from the same internal state, so they always agree. A client that rewrites one and forgets the other contradicts itself — visible from a single request, with no history, no state and no network call, which makes it one of the cheapest high-value checks there is."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Most of it is "
      ],
      [
       "code",
       "strong"
      ],
      [
       "t",
       " rather than "
      ],
      [
       "code",
       "certain"
      ],
      [
       "t",
       ", because the population that rewrites a User-Agent without touching Client Hints includes privacy extensions and corporate middleboxes as well as scrapers."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "fetch-metadata",
   "group": "Single-request detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling strong"
   ],
   "summary": "Sec-Fetch-Site, -Mode, -Dest, -User.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "code",
       "Sec-Fetch-Site"
      ],
      [
       "t",
       ", "
      ],
      [
       "code",
       "-Mode"
      ],
      [
       "t",
       ", "
      ],
      [
       "code",
       "-Dest"
      ],
      [
       "t",
       ", "
      ],
      [
       "code",
       "-User"
      ],
      [
       "t",
       "."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "These are "
      ],
      [
       "b",
       "forbidden headers"
      ],
      [
       "t",
       ": page JavaScript cannot set or alter them, so in a real browser they are generated by the network stack from the actual context of the request. That makes them unusually hard to forge from inside a page — and their "
      ],
      [
       "i",
       "absence"
      ],
      [
       "t",
       " on an engine known to send them is informative."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "It knows which engine versions ship them (Blink 76+, Gecko 90+), so an old browser is not accused of missing something it never sent."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "accept-signature",
   "group": "Single-request detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling strong"
   ],
   "summary": "Accept and Accept-Language as a fingerprint of what the client will do with the response.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "code",
       "Accept"
      ],
      [
       "t",
       " and "
      ],
      [
       "code",
       "Accept-Language"
      ],
      [
       "t",
       " as a fingerprint of what the client will do with the response."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "A browser asking for a page sends a long, specific "
      ],
      [
       "code",
       "Accept"
      ],
      [
       "t",
       " describing the document formats it renders. A scraper sends "
      ],
      [
       "code",
       "*/*"
      ],
      [
       "t",
       " because it will take anything and parse it itself. Malformed language lists — values that are not RFC 9110 language ranges — are a separate and stronger signal, because a browser cannot produce one."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "probe-signature",
   "group": "Single-request detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling strong"
   ],
   "summary": "What is this request asking for?",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "What is this request "
      ],
      [
       "i",
       "asking for"
      ],
      [
       "t",
       "?"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Every other detector reads the client; this one reads the target, and it exists to close a gap the rest cannot: the scanner that does not announce itself. "
      ],
      [
       "code",
       "self-identified"
      ],
      [
       "t",
       " catches sqlmap and Nikto because they say so, and a great deal of hostile traffic does say so. The rest arrives wearing an ordinary browser User-Agent and asks for "
      ],
      [
       "code",
       "/.env"
      ],
      [
       "t",
       ", "
      ],
      [
       "code",
       "/wp-admin/setup-config.php"
      ],
      [
       "t",
       ", "
      ],
      [
       "code",
       "/../../etc/passwd"
      ],
      [
       "t",
       " or a path with a SQL payload in the query string."
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "ts",
     "code": "probeSignatureDetector({ extraPaths: [\"/internal/admin\"] })"
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "target-integrity",
   "group": "Single-request detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling strong"
   ],
   "summary": "How was this target spelled?",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "How was this target "
      ],
      [
       "i",
       "spelled"
      ],
      [
       "t",
       "?"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "code",
       "probe-signature"
      ],
      [
       "t",
       " above reads what a request asked for. This one reads how it asked, and it exists because the two are not the same question — and because the answer to the second is normally destroyed before any detector sees it."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Every detector reads "
      ],
      [
       "code",
       "facts.path"
      ],
      [
       "t",
       ", which is normalised: decoded once, backslashes and doubled slashes collapsed, "
      ],
      [
       "code",
       "."
      ],
      [
       "t",
       " and "
      ],
      [
       "code",
       ".."
      ],
      [
       "t",
       " resolved. That is not optional — a rule scoped to "
      ],
      [
       "code",
       "/admin"
      ],
      [
       "t",
       " has to hold against "
      ],
      [
       "code",
       "/%61dmin"
      ],
      [
       "t",
       " and "
      ],
      [
       "code",
       "/./admin"
      ],
      [
       "t",
       " or it is not a rule. It is also exactly what makes an evasive target arrive looking ordinary:"
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "",
     "code": "GET /%2e%2e%2f%2e%2e%2fapp/config.yml      →  facts.path = \"/app/config.yml\""
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Which is a page nobody has, on no wordlist, indistinguishable from a broken link. So the target as it arrived is kept in "
      ],
      [
       "code",
       "facts.rawPath"
      ],
      [
       "t",
       " — and only when it differs from the normalised form, which on ordinary traffic it does not — and this reads it."
      ]
     ]
    },
    {
     "kind": "table",
     "head": [
      [
       [
        "t",
        "Spelling"
       ]
      ],
      [
       [
        "t",
        "Tier"
       ]
      ]
     ],
     "rows": [
      [
       [
        [
         "t",
         "Encoded its own encoding, so one decoding pass leaves it still encoded"
        ]
       ],
       [
        [
         "code",
         "strong"
        ]
       ]
      ],
      [
       [
        [
         "t",
         "Wrote a traversal with its dots and slashes percent-encoded"
        ]
       ],
       [
        [
         "code",
         "strong"
        ]
       ]
      ],
      [
       [
        [
         "t",
         "Carried a control character, raw or encoded"
        ]
       ],
       [
        [
         "code",
         "strong"
        ]
       ]
      ],
      [
       [
        [
         "t",
         "Addressed the target to a proxy — "
        ],
        [
         "code",
         "GET http://elsewhere/"
        ],
        [
         "t",
         " at an origin server"
        ]
       ],
       [
        [
         "code",
         "strong"
        ]
       ]
      ],
      [
       [
        [
         "t",
         "Hid a path separator inside a segment"
        ]
       ],
       [
        [
         "code",
         "moderate"
        ]
       ]
      ],
      [
       [
        [
         "t",
         "Walked up out of the site root, written plainly"
        ]
       ],
       [
        [
         "code",
         "moderate"
        ]
       ]
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "b",
       "Nothing here is "
      ],
      [
       "code",
       "certain"
      ],
      [
       "b",
       ", and the closest call says why."
      ],
      [
       "t",
       " A path segment that carries a URL as "
      ],
      [
       "i",
       "data"
      ],
      [
       "t",
       " — "
      ],
      [
       "code",
       "/redirect/https%3A%2F%2Fexample.com%2Fa"
      ],
      [
       "t",
       " — is encoded once to sit in a path and encoded again by whatever built the link around it. That is a real pattern on real sites and it produces "
      ],
      [
       "code",
       "%252e"
      ],
      [
       "t",
       " honestly. A deliberate act with no ordinary cause is not the same thing as one admitting no benign explanation, and only the second may close a door."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "The plain-traversal row is the one a "
      ],
      [
       "i",
       "broken"
      ],
      [
       "t",
       " client produces as readily as a hostile one, so it has a switch:"
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "ts",
     "code": "targetIntegrityDetector({ reportPlainTraversal: false })"
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "All of these share the family "
      ],
      [
       "code",
       "evasive-target"
      ],
      [
       "t",
       ". One target usually trips several — a traversal is normally encoded and an encoded traversal is often double-encoded — and that is one act seen three ways, not three reasons."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "tls-fingerprint",
   "group": "Single-request detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling strong"
   ],
   "summary": "Compares an edge-supplied JA3/JA4 handshake fingerprint against the client the User-Agent claims to be.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Compares an edge-supplied JA3/JA4 handshake fingerprint against the client the User-Agent claims to be."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "This is the signal that survives a scraper copying every header perfectly: the TLS handshake is produced by the client's TLS stack rather than by its HTTP code, so a Go or Python program wearing Chrome's headers still shakes hands like Go or Python."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "The library does not compute fingerprints — it cannot see the handshake — so it reads one your edge computed:"
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "ts",
     "code": "createFetchAdapter(handler, { tlsFingerprintHeader: \"cf-ja3-hash\" });\n\ntlsFingerprintDetector({ profiles: { \"<ja3 hash>\": { name: \"Chrome 122\", engine: \"blink\" } } })"
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Without profiles it stays quiet rather than guessing."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "ip-intelligence",
   "group": "Single-request detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling certain"
   ],
   "summary": "What is known about where this came from. Two range sets, treated very differently.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "What is known about where this came from. Two range sets, treated very differently."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "code",
       "denylist"
      ],
      [
       "b",
       " is "
      ],
      [
       "code",
       "certain"
      ],
      [
       "t",
       " — and the justification is not technical. "
      ],
      [
       "i",
       "You"
      ],
      [
       "t",
       " configured it. The library is not inferring anything; it is carrying out an instruction you gave about addresses you decided about."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "code",
       "datacenterRanges"
      ],
      [
       "b",
       " is "
      ],
      [
       "code",
       "moderate"
      ],
      [
       "t",
       " — a server address is a fact about hosting, not about intent. VPNs, corporate egress and privacy relays all live there, and so do plenty of people."
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "ts",
     "code": "new BotHandler({\n  denylist: [\"203.0.113.0/24\"],\n  datacenterRanges: [\"198.51.100.0/16\"],\n});"
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "The library ships "
      ],
      [
       "b",
       "no address data"
      ],
      [
       "t",
       " and refuses to guess any; see design decisions."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "b",
       "Loading a feed."
      ],
      [
       "t",
       " "
      ],
      [
       "code",
       "fetchAddressList"
      ],
      [
       "t",
       " reads a published list — a reputation feed, a hosting provider's own ranges — over the same hardened path the crawler ranges use: HTTPS only, a size cap, "
      ],
      [
       "code",
       "#"
      ],
      [
       "t",
       " and "
      ],
      [
       "code",
       ";"
      ],
      [
       "t",
       " comments stripped, JSON "
      ],
      [
       "code",
       "prefixes"
      ],
      [
       "t",
       " documents or one prefix per line, and a list that is empty, oversized or contains a block big enough to matter is refused "
      ],
      [
       "b",
       "whole"
      ],
      [
       "t",
       " rather than in part."
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "ts",
     "code": "import { fetchAddressList } from \"@osqd/bothandlerjs\";\n\nconst prefixes = await fetchAddressList({ id: \"denylist\", url: \"https://example.org/drop.txt\" });\ndetector.updateRanges(\"denylist\", prefixes);"
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Two steps, on purpose: fetching is the part that can fail, and installing is the part that changes what happens to somebody. Nothing is fetched on a schedule unless you schedule it."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "And think hard before pointing that at "
      ],
      [
       "code",
       "denylist"
      ],
      [
       "t",
       " rather than "
      ],
      [
       "code",
       "datacenter"
      ],
      [
       "t",
       ". A denylist entry does not corroborate anything — it decides, and it blocks people. A feed is somebody else's judgement about an address, refreshed on somebody else's schedule, and an address that was a bot last month may be a customer's home connection this month."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "trap",
   "group": "Single-request detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling certain"
   ],
   "summary": "A path no link points at, a form field no rendered browser shows, a header only a script would echo. Reaching one requires reading the page as data rather than as a page.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "A path no link points at, a form field no rendered browser shows, a header only a script would echo. Reaching one requires reading the page as data rather than as a page."
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "ts",
     "code": "import { renderTrapLink, trapRobotsEntries, DEFAULT_TRAP_PATHS } from \"@osqd/bothandlerjs\";\n\napp.get(\"/\", (_req, res) => res.send(page + renderTrapLink()));\n\n// And publish the same paths, so a crawler that obeys robots.txt never sees them.\napp.get(\"/robots.txt\", (_req, res) => res.type(\"text/plain\").send(trapRobotsEntries(DEFAULT_TRAP_PATHS)));"
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "The trap paths belong in your "
      ],
      [
       "code",
       "robots.txt"
      ],
      [
       "t",
       " as "
      ],
      [
       "code",
       "Disallow"
      ],
      [
       "t",
       ", which is what makes the evidence fair: a crawler that obeys robots never sees them, so touching one is a decision."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "cadence",
   "group": "Behavioural detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling moderate"
   ],
   "summary": "Is this actor's rhythm human?",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Is this actor's "
      ],
      [
       "i",
       "rhythm"
      ],
      [
       "t",
       " human?"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "People generate ragged inter-arrival times: they read, scroll, get distracted, open three tabs, then nothing for four minutes. A loop calling "
      ],
      [
       "code",
       "setInterval"
      ],
      [
       "t",
       " produces gaps clustered tightly around one value, and the coefficient of variation makes that visible in a single number."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "The check is on "
      ],
      [
       "i",
       "regularity"
      ],
      [
       "t",
       ", not speed, which is what makes it complementary to "
      ],
      [
       "code",
       "rate-anomaly"
      ],
      [
       "t",
       ": a slow, polite scraper pacing itself at one request every five seconds is invisible to a rate check and obvious to this one."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "rate-anomaly",
   "group": "Behavioural detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling moderate"
   ],
   "summary": "How fast is this actor going?",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "How fast is this actor going?"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Rate is the signal people reach for first and trust most, and it deserves the least trust of anything here. The "
      ],
      [
       "i",
       "actor"
      ],
      [
       "t",
       " behind a high rate is frequently not one client: a corporate NAT, a CGNAT pool, a university, a VPN exit and a shared office all present hundreds of real people under one key."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "So it is deliberately conservative, and it is the detector most improved by a better "
      ],
      [
       "code",
       "actorKey"
      ],
      [
       "t",
       "."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "crawl-breadth",
   "group": "Behavioural detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling weak"
   ],
   "summary": "Reading the site, or enumerating it?",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Reading the site, or enumerating it?"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "A person revisits: they land on an article, go back to the index, follow a related link, return. Their ratio of distinct paths to total requests settles well below one. A crawler walking a sitemap almost never revisits, so its ratio sits near one."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "code",
       "weak"
      ],
      [
       "t",
       ", because a "
      ],
      [
       "i",
       "welcome"
      ],
      [
       "t",
       " crawler produces exactly this shape and so does a person on a first visit to a documentation site."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "blended-identity",
   "group": "Behavioural detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling strong"
   ],
   "summary": "What a series of claims says, as opposed to what one claim says.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "What a "
      ],
      [
       "i",
       "series"
      ],
      [
       "t",
       " of claims says, as opposed to what one claim says."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Every other identity check here reads a single request: this User-Agent names this bot, and that claim is either confirmable or it is not. The set of identities an actor has claimed over time is a different object, and some sets are self-contradictory in a way no member of them is."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Three readings:"
      ]
     ]
    },
    {
     "kind": "list",
     "items": [
      [
       [
        "b",
        "Several security tools."
       ],
       [
        "t",
        " One address arriving as two or more named scanners is a scan, not a coincidence."
       ]
      ],
      [
       [
        "b",
        "Several verifiable crawlers."
       ],
       [
        "t",
        " At most one of Googlebot, Bingbot and Yandex can be true of an address, because each publishes a proof tied to addresses it controls. The contradiction is visible from the claims alone — which matters most when DNS is unreachable and neither claim can be refuted on its own."
       ]
      ],
      [
       [
        "b",
        "A crawler that also probes."
       ],
       [
        "t",
        " An actor that sent a scanner payload "
       ],
       [
        "i",
        "and"
       ],
       [
        "t",
        " claimed to be a search crawler has told you which of the two is the lie."
       ]
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "b",
       "These hold under the default address-based actor key"
      ],
      [
       "t",
       ", which is why they are on by default and "
      ],
      [
       "code",
       "identity-rotation"
      ],
      [
       "t",
       " is not. A NAT gateway presents many browsers — that is exactly what makes counting User-Agents useless there — but it does not present sqlmap "
      ],
      [
       "i",
       "and"
      ],
      [
       "t",
       " nikto, and it does not claim to be Googlebot "
      ],
      [
       "i",
       "and"
      ],
      [
       "t",
       " Bingbot. The innocent explanation for a hundred browsers behind one address is an office; there is no corresponding one for these."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "code",
       "strong"
      ],
      [
       "t",
       ", not "
      ],
      [
       "code",
       "certain"
      ],
      [
       "t",
       ". Trusting the wrong forwarded header collapses every client onto one address, and then two genuinely different crawlers produce this exact set — so it may contribute to a denial and may not be the whole of one."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "id-enumeration",
   "group": "Behavioural detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling moderate"
   ],
   "summary": "Somebody working through the identifiers rather than following the links.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Somebody working through the identifiers rather than following the links."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "code",
       "crawl-breadth"
      ],
      [
       "t",
       " sees this as \"many distinct paths\" — which is also what it sees when a person reads a documentation site, so it stays "
      ],
      [
       "code",
       "weak"
      ],
      [
       "t",
       " and nothing separates the two. Measured before this existed: "
      ],
      [
       "code",
       "/user/1"
      ],
      [
       "t",
       " through "
      ],
      [
       "code",
       "/user/120"
      ],
      [
       "t",
       " in order scored 57, a hundred and twenty scattered ids scored 57, and ordinary article paths scored 57."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "What separates them is not "
      ],
      [
       "i",
       "which"
      ],
      [
       "t",
       " ids were asked for but whether they "
      ],
      [
       "b",
       "cover a range"
      ],
      [
       "t",
       ". People arrive at ids through links, and links do not densely enumerate an integer interval; a harvester does nothing else. Thirty requests reaching from id 1 to id 33 is a walk; thirty scattered across a hundred thousand is somebody reading."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "It costs three numbers per path shape — a count, a lowest and a highest — rather than a list of every id seen, which is what makes it affordable for an actor that asks for ten thousand of them. The last numeric segment is taken as the identifier, so in "
      ],
      [
       "code",
       "/api/v2/orders/42"
      ],
      [
       "t",
       " the version is part of the shape and the order id is the walk. Numbers too large to be a counter are ignored: nobody walks epoch seconds."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "code",
       "moderate"
      ],
      [
       "t",
       ", with the bar set high on purpose. Products in one category often carry consecutive ids, so somebody browsing a catalogue produces a smaller version of this."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "probe-volume",
   "group": "Behavioural detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling moderate"
   ],
   "summary": "An actor that is looking for something rather than reading anything.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "An actor that is looking for something rather than reading anything."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "The oldest tell there is for a scanner, and the one this library could not see. Every verdict here is reached "
      ],
      [
       "i",
       "before"
      ],
      [
       "t",
       " the response exists — that is what lets it shape the response, and it is also what hides the status code from it. So the application reports it back:"
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "ts",
     "code": "const { outcome } = await handler.handle(facts);\n// …your application answers…\nhandler.recordOutcome(facts, response.statusCode);"
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Every bundled adapter does this for you — Node and Express on the response's "
      ],
      [
       "code",
       "finish"
      ],
      [
       "t",
       ", Fastify on the reply's, Koa from the status the middleware chain settled on, and the Fetch wrapper from the "
      ],
      [
       "code",
       "Response"
      ],
      [
       "t",
       " it returns. You only need the call above if you drive the engine yourself. Nothing else depends on it: every other detector works unchanged if you never call it, and this one is simply absent."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Counts "
      ],
      [
       "b",
       "404 and 410 only"
      ],
      [
       "t",
       ". A 403 is usually this library's own doing, and counting it would let a rule that challenges an actor manufacture the evidence for having challenged it. A 500 is the site's problem and says nothing about the client."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "code",
       "moderate"
      ],
      [
       "t",
       ", because a site that has just moved its URLs produces exactly this shape from perfectly ordinary readers, and so does a feed reader working through removed articles. Eighty per cent of at least twenty reported responses, by default."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "transport-coherence",
   "group": "Behavioural detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling moderate"
   ],
   "summary": "How a claimed browser moves, rather than what it says.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "How a claimed browser "
      ],
      [
       "i",
       "moves"
      ],
      [
       "t",
       ", rather than what it says."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "The header checks read one request against the client it claims to be. This reads the transport underneath and the verbs across a visit — harder to copy, because neither is in the part of a request most tooling lets you set."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Two things. A claimed browser that negotiated "
      ],
      [
       "b",
       "HTTP/1.0"
      ],
      [
       "t",
       ", which no shipping browser has offered in over a decade. And a visit made "
      ],
      [
       "b",
       "entirely of HEAD"
      ],
      [
       "t",
       ": one HEAD is a browser checking a link it is about to follow or a cache revalidating, but a whole visit of them is something checking what exists without reading any of it."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Both were measured as blind spots before this existed — a client claiming Chrome 120 over HTTP/1.0, and one whose whole visit was HEAD, each scored exactly what the honest control scored."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Capped at "
      ],
      [
       "code",
       "moderate"
      ],
      [
       "t",
       ", for different reasons each. HTTP/1.0 is not always the client's doing: a few older load balancers speak it to the origin, and behind one of those every request looks like this — which is what "
      ],
      [
       "code",
       "transportCoherenceDetector({ legacyHttp: false })"
      ],
      [
       "t",
       " is for. An all-HEAD visit is a stronger shape, but a link checker is a real and mostly harmless thing to be."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "b",
       "It cannot simply be made NAT-safe, and it is worth saying why."
      ],
      [
       "t",
       " A rotator changes the User-Agent and nothing else, so \"several User-Agents behind a single header shape\" looks like a clean way to separate it from a gateway. Measured, it is not: ten real browser profiles collapse to six stable header shapes, and Chrome, Edge, Opera and Chromium on Linux share one — they are the same engine sending the same headers in the same order. An office running Chrome and Edge produces that signature exactly. The narrower actor key is the fix; there is no header trick that substitutes for it."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "parameter-sweep",
   "group": "Behavioural detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling weak"
   ],
   "summary": "The collection crawl-breadth cannot see.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "The collection "
      ],
      [
       "code",
       "crawl-breadth"
      ],
      [
       "t",
       " cannot see."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Breadth counts distinct "
      ],
      [
       "i",
       "paths"
      ],
      [
       "t",
       ", and a path carries no query string — so the shape it reads as \"somebody rereading one page\" is also the shape of enumerating a catalogue. "
      ],
      [
       "code",
       "/products?page=1"
      ],
      [
       "t",
       " through "
      ],
      [
       "code",
       "?page=200"
      ],
      [
       "t",
       " is one path and two hundred requests. Measured on the same two hundred requests expressed both ways: as distinct paths they scored 62 and were called "
      ],
      [
       "code",
       "suspected-bot"
      ],
      [
       "t",
       "; as "
      ],
      [
       "code",
       "?page=N"
      ],
      [
       "t",
       " they scored 55 and passed as "
      ],
      [
       "code",
       "unknown"
      ],
      [
       "t",
       ". Paginated collection is not an exotic case — it is how catalogues, search results and APIs are actually taken."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "So this counts the other thing: distinct parameterisations, and how many of them stack onto a single path. Both halves matter. A high variant count on its own is ordinary — a shop's own visitors filter and sort — and it is the "
      ],
      [
       "i",
       "concentration"
      ],
      [
       "t",
       " that separates a person changing their mind from a machine walking an index."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "code",
       "weak"
      ],
      [
       "t",
       ", for the same reason as breadth: a person paging through search results produces a smaller version of exactly this. Its value is as a second signal beside an actor that has already failed something sharper."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "identity-rotation",
   "group": "Behavioural detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling moderate",
    "off by default"
   ],
   "summary": "One actor, several User-Agents. A single client does not change its User-Agent mid-session; something that does is cycling through a spoofing list.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "One actor, several User-Agents. A single client does not change its User-Agent mid-session; something that does is cycling through a spoofing list."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "b",
       "Off by default, and think before enabling it."
      ],
      [
       "t",
       " With the default address-based actor key, a corporate NAT presents a hundred people's browsers as one actor with a hundred User-Agents — which is this detector's exact signature and is entirely innocent. Switching it on without also narrowing "
      ],
      [
       "code",
       "actorKey"
      ],
      [
       "t",
       " raises a startup warning, because it is a decision whose consequences are invisible until real visitors are being challenged. Enable it when your "
      ],
      [
       "code",
       "actorKey"
      ],
      [
       "t",
       " identifies a session rather than a network."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "session-integrity",
   "group": "Behavioural detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling moderate"
   ],
   "summary": "Does this client hold a session?",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Does this client hold a session?"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "A browser accumulates state: once your server has set anything — a session cookie, a consent flag, an A/B bucket — a real browser sends it back on every subsequent request. A stateless HTTP client sends nothing back however many times it visits."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "It only speaks about clients that "
      ],
      [
       "i",
       "claim"
      ],
      [
       "t",
       " to be browsers, and only after your origin has had a chance to set something."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "browsing-coherence",
   "group": "Behavioural detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling moderate (human)"
   ],
   "summary": "The one that argues the other way.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "The one that argues the other way."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "It reports the marks of a real browsing session — a cache validator ("
      ],
      [
       "code",
       "If-None-Match"
      ],
      [
       "t",
       "), a cookie jar, a same-site navigation, a plausible "
      ],
      [
       "code",
       "Referer"
      ],
      [
       "t",
       " chain — as "
      ],
      [
       "b",
       "human"
      ],
      [
       "t",
       " evidence, which the scoring model subtracts from the bot score."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Without it the model has an asymmetry that shows up as false positives on exactly the people least able to afford them: a researcher on a shared university address reading forty pages accumulates four suspicions and nothing at all in their defence."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "clearance",
   "group": "Behavioural detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling certain (human)"
   ],
   "summary": "Reads a signed clearance token the client already holds. The library's only source of human-pointing evidence that is not a guess about headers, and the levels are exact because overstating any of them would undo the design:",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Reads a signed clearance token the client already holds. The library's only source of human-pointing evidence that is not a guess about headers, and the levels are exact because overstating any of them would undo the design:"
      ]
     ]
    },
    {
     "kind": "table",
     "head": [
      [
       [
        "t",
        "Level"
       ]
      ],
      [
       [
        "t",
        "Certainty"
       ]
      ],
      []
     ],
     "rows": [
      [
       [
        [
         "code",
         "operator"
        ]
       ],
       [
        [
         "code",
         "certain"
        ]
       ],
       [
        [
         "t",
         "Your application said this is a person. We believe you."
        ]
       ]
      ],
      [
       [
        [
         "code",
         "pow"
        ]
       ],
       [
        [
         "code",
         "moderate"
        ]
       ],
       [
        [
         "t",
         "A proof of work was solved. A headless browser solves it too."
        ]
       ]
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "See the challenge."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "client-signals",
   "group": "Behavioural detectors",
   "facts": [
    "cheap",
    "always",
    "ceiling moderate"
   ],
   "summary": "Reads what the optional browser script reported: navigator.webdriver, an empty language list, zero screen dimensions, a platform that disagrees with the User-Agent, whether a trusted interaction happened.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Reads what the optional browser script reported: "
      ],
      [
       "code",
       "navigator.webdriver"
      ],
      [
       "t",
       ", an empty language list, zero screen dimensions, a platform that disagrees with the User-Agent, whether a trusted interaction happened."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "b",
       "Capped at "
      ],
      [
       "code",
       "moderate"
      ],
      [
       "b",
       ", hard."
      ],
      [
       "t",
       " Every value here was produced by JavaScript running inside the client, which is the one place an adversary has complete control. A framework that wants "
      ],
      [
       "code",
       "navigator.webdriver"
      ],
      [
       "t",
       " to read "
      ],
      [
       "code",
       "false"
      ],
      [
       "t",
       " sets it to "
      ],
      [
       "code",
       "false"
      ],
      [
       "t",
       ". What this genuinely catches is automation that never bothered to hide — which is a large share of real bot traffic — and what it must never do is convince you that a clean report means a person."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "crawler-verification",
   "group": "Confirming detectors",
   "facts": [
    "io",
    "confirming",
    "ceiling certain"
   ],
   "summary": "Confirms or refutes a claimed crawler identity. Runs only when a signature matched, because with no claim there is nothing to confirm and no lookup to make.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Confirms or refutes a claimed crawler identity. Runs only when a signature matched, because with no claim there is nothing to confirm and no lookup to make."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Two mechanisms, depending on what the operator publishes:"
      ]
     ]
    },
    {
     "kind": "list",
     "items": [
      [
       [
        "b",
        "Forward-confirmed reverse DNS."
       ],
       [
        "t",
        " "
       ],
       [
        "code",
        "PTR"
       ],
       [
        "t",
        " the address, check the name is under the crawler's domain, then resolve that name forward and check it comes back to the same address. A confirmation is "
       ],
       [
        "code",
        "verified-bot"
       ],
       [
        "t",
        "; a "
       ],
       [
        "b",
        "refutation"
       ],
       [
        "t",
        " is "
       ],
       [
        "code",
        "certain"
       ],
       [
        "t",
        " evidence of an impersonator, and the strongest thing this library ever concludes about a forgery."
       ]
      ],
      [
       [
        "b",
        "Published address ranges."
       ],
       [
        "t",
        " A lookup rather than a round trip. See verifying a crawler."
       ]
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "A resolver that is merely "
      ],
      [
       "i",
       "unhappy"
      ],
      [
       "t",
       " must reach a different verdict from one that "
      ],
      [
       "i",
       "disproves"
      ],
      [
       "t",
       " the claim, and it does: a timeout produces no evidence at all."
      ]
     ]
    }
   ],
   "source": "docs/detection/detectors.md"
  },
  {
   "kind": "detector",
   "id": "identity-drift",
   "group": "Installed with probe",
   "facts": [
    "ceiling strong",
    "needs probe"
   ],
   "summary": "The identity claimed now against the one claimed when the marker was issued",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "b",
       "Reads: "
      ],
      [
       "t",
       "The identity claimed now against the one claimed when the marker was issued"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "b",
       "With "
      ],
      [
       "code",
       "probe"
      ],
      [
       "t",
       " — a signed marker cookie this server issues and reads back, which identifies a "
      ],
      [
       "i",
       "client"
      ],
      [
       "t",
       " across requests rather than an address:"
      ]
     ]
    },
    {
     "kind": "h",
     "text": [
      [
       "t",
       "Identity drift, and why the parts are weighed separately"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "A "
      ],
      [
       "b",
       "browser family"
      ],
      [
       "t",
       " that changes — Chrome to curl, Firefox to Googlebot — has no benign reading. Software does not change what it is, so one of the two claims is false and the evidence is "
      ],
      [
       "code",
       "strong"
      ],
      [
       "t",
       "."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "A "
      ],
      [
       "b",
       "platform"
      ],
      [
       "t",
       " that changes does have a benign reading, and a common one: \"Request desktop site\" on a phone rewrites the User-Agent to claim a desktop, and the person doing it is a person. A language changes when somebody changes their language. Those are reported at "
      ],
      [
       "code",
       "moderate"
      ],
      [
       "t",
       " and named as the soft case in the summary, or turned off:"
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "ts",
     "code": "identityDriftDetector({ reportSoftDrift: false });"
    }
   ],
   "source": "docs/detection/correlation.md"
  },
  {
   "kind": "detector",
   "id": "marker-integrity",
   "group": "Installed with probe",
   "facts": [
    "ceiling strong",
    "needs probe"
   ],
   "summary": "A marker presented with a signature this server could not have produced",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "b",
       "Reads: "
      ],
      [
       "t",
       "A marker presented with a signature this server could not have produced"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "b",
       "With "
      ],
      [
       "code",
       "probe"
      ],
      [
       "t",
       " — a signed marker cookie this server issues and reads back, which identifies a "
      ],
      [
       "i",
       "client"
      ],
      [
       "t",
       " across requests rather than an address:"
      ]
     ]
    }
   ],
   "source": "docs/detection/correlation.md"
  },
  {
   "kind": "detector",
   "id": "marker-fanout",
   "group": "Installed with probe",
   "facts": [
    "ceiling moderate",
    "needs probe"
   ],
   "summary": "Distinct networks one marker has been presented from",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "b",
       "Reads: "
      ],
      [
       "t",
       "Distinct networks one marker has been presented from"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "b",
       "With "
      ],
      [
       "code",
       "probe"
      ],
      [
       "t",
       " — a signed marker cookie this server issues and reads back, which identifies a "
      ],
      [
       "i",
       "client"
      ],
      [
       "t",
       " across requests rather than an address:"
      ]
     ]
    }
   ],
   "source": "docs/detection/correlation.md"
  },
  {
   "kind": "detector",
   "id": "marker-persistence",
   "group": "Installed with probe",
   "facts": [
    "ceiling moderate",
    "needs probe"
   ],
   "summary": "A client that sends cookies but never returns the one this server set",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "b",
       "Reads: "
      ],
      [
       "t",
       "A client that sends cookies but never returns the one this server set"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "b",
       "With "
      ],
      [
       "code",
       "probe"
      ],
      [
       "t",
       " — a signed marker cookie this server issues and reads back, which identifies a "
      ],
      [
       "i",
       "client"
      ],
      [
       "t",
       " across requests rather than an address:"
      ]
     ]
    },
    {
     "kind": "h",
     "text": [
      [
       "t",
       "Not returning the marker, and who that describes"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "code",
       "marker-persistence"
      ],
      [
       "t",
       " deliberately says nothing about a client that sends "
      ],
      [
       "b",
       "no"
      ],
      [
       "t",
       " cookies at all. That client is "
      ],
      [
       "code",
       "session-integrity"
      ],
      [
       "t",
       "'s business, and it already reports it at a weight chosen for the people who produce it — people who block cookies. Having both speak is one observation counted twice, landing on exactly that population: measured on the corpus, the overlapping version took the "
      ],
      [
       "code",
       "cookies-blocked"
      ],
      [
       "t",
       " case from 21 to 38 and put +24 on five ordinary browsing sessions."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "So this asks the narrower question only a marker can answer — the client is demonstrably keeping cookies, and ours is not among them — and the two share an evidence "
      ],
      [
       "code",
       "family"
      ],
      [
       "t",
       ", so even where both apply the stronger stands rather than the two summing."
      ]
     ]
    }
   ],
   "source": "docs/detection/correlation.md"
  },
  {
   "kind": "detector",
   "id": "challenge-reaction",
   "group": "Installed with challenge",
   "facts": [
    "ceiling strong",
    "needs challenge"
   ],
   "summary": "What a client did in the seconds after it was challenged",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "b",
       "Reads: "
      ],
      [
       "t",
       "What a client did in the seconds after it was challenged"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "b",
       "With "
      ],
      [
       "code",
       "challenge"
      ],
      [
       "t",
       " — reactions to a question this server chose to ask:"
      ]
     ]
    },
    {
     "kind": "h",
     "text": [
      [
       "t",
       "Reaction beats observation"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "code",
       "challenge-reaction"
      ],
      [
       "t",
       " is the strongest idea here, and the reason is structural. Every other detector reads traffic that would have happened anyway and argues backwards from it. This one reads a response to a stimulus "
      ],
      [
       "b",
       "we chose"
      ],
      [
       "t",
       ": we decided when the challenge went out, so a client that changes what it claims to be within seconds of receiving one is reacting to it. There was no reason to look at that moment except that we created it."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "It reports two things — a changed identity, and never answering at all across repeated asks. The first is "
      ],
      [
       "code",
       "strong"
      ],
      [
       "t",
       " when a marker ties the two requests together and "
      ],
      [
       "code",
       "moderate"
      ],
      [
       "t",
       " when only the address does, because that is genuinely how much less an address-based join is worth. The second is capped at "
      ],
      [
       "code",
       "moderate"
      ],
      [
       "t",
       " forever: a person with JavaScript disabled produces it every time, and they are a person."
      ]
     ]
    }
   ],
   "source": "docs/detection/correlation.md"
  },
  {
   "kind": "detector",
   "id": "challenge-integrity",
   "group": "Installed with challenge",
   "facts": [
    "ceiling moderate",
    "needs challenge"
   ],
   "summary": "Solutions replayed, or returned faster than the puzzle allows",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "b",
       "Reads: "
      ],
      [
       "t",
       "Solutions replayed, or returned faster than the puzzle allows"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "b",
       "With "
      ],
      [
       "code",
       "challenge"
      ],
      [
       "t",
       " — reactions to a question this server chose to ask:"
      ]
     ]
    }
   ],
   "source": "docs/detection/correlation.md"
  },
  {
   "kind": "detector",
   "id": "distributed-walk",
   "group": "Installed with site",
   "facts": [
    "ceiling moderate",
    "needs site"
   ],
   "summary": "A numeric range walked across many clients, none of which walks enough of it alone",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "b",
       "Reads: "
      ],
      [
       "t",
       "A numeric range walked across many clients, none of which walks enough of it alone"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "b",
       "With "
      ],
      [
       "code",
       "site"
      ],
      [
       "t",
       " — a warmed-up baseline of what the rest of your traffic looks like:"
      ]
     ]
    },
    {
     "kind": "h",
     "text": [
      [
       "t",
       "What each one is really for"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "code",
       "distributed-walk"
      ],
      [
       "t",
       " addresses the one threat per-actor thresholds miss "
      ],
      [
       "b",
       "by construction"
      ],
      [
       "t",
       ". Split an id range across five hundred addresses at one request a minute each and every actor is unremarkable, "
      ],
      [
       "code",
       "id-enumeration"
      ],
      [
       "t",
       " never fires for anybody, and the range is still walked end to end. It is only visible in the union. What separates it from a busy shop is that enumeration "
      ],
      [
       "i",
       "covers"
      ],
      [
       "t",
       " a contiguous range and visits each id about once, while real readers cluster on popular items and return to them — so coverage and the revisit ratio must both agree, and either alone would report an ordinary catalogue."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "code",
       "distributed-walk"
      ],
      [
       "b",
       " needs both of its bounds."
      ],
      [
       "t",
       " The revisit ratio is checked from above "
      ],
      [
       "i",
       "and"
      ],
      [
       "t",
       " below, and the lower bound is what makes it usable on a real site. Ids spread across a six-figure catalogue coarsen the bitmap until one bucket stands for hundreds of ids; ordinary browsing then touches nearly every bucket, so coverage reads 1.0 and the estimated id count runs far ahead of the requests that were actually made. Requiring the visits to account for the ids claimed is what rejects an estimate that has left the evidence behind — measured on a simulated shop, sixty long-tail shoppers were reported before that bound existed and none after."
      ]
     ]
    }
   ],
   "source": "docs/detection/correlation.md"
  },
  {
   "kind": "detector",
   "id": "path-novelty",
   "group": "Installed with site",
   "facts": [
    "ceiling moderate",
    "needs site"
   ],
   "summary": "A client whose requests are almost all for paths nobody else has asked for",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "b",
       "Reads: "
      ],
      [
       "t",
       "A client whose requests are almost all for paths nobody else has asked for"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "b",
       "With "
      ],
      [
       "code",
       "site"
      ],
      [
       "t",
       " — a warmed-up baseline of what the rest of your traffic looks like:"
      ]
     ]
    },
    {
     "kind": "h",
     "text": [
      [
       "t",
       "What each one is really for"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "code",
       "path-novelty"
      ],
      [
       "t",
       " is a self-maintaining wordlist. A wordlist is a list of paths that exist on "
      ],
      [
       "i",
       "some"
      ],
      [
       "t",
       " sites; on yours most of them do not exist and nobody has ever asked for them. It catches the scanner whose list is newer than the one this library ships."
      ]
     ]
    }
   ],
   "source": "docs/detection/correlation.md"
  },
  {
   "kind": "detector",
   "id": "miss-baseline",
   "group": "Installed with site",
   "facts": [
    "ceiling moderate",
    "needs site"
   ],
   "summary": "This client's miss rate against the site's own",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "b",
       "Reads: "
      ],
      [
       "t",
       "This client's miss rate against the site's own"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "b",
       "With "
      ],
      [
       "code",
       "site"
      ],
      [
       "t",
       " — a warmed-up baseline of what the rest of your traffic looks like:"
      ]
     ]
    },
    {
     "kind": "h",
     "text": [
      [
       "t",
       "What each one is really for"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "code",
       "miss-baseline"
      ],
      [
       "t",
       " is "
      ],
      [
       "code",
       "probe-volume"
      ],
      [
       "t",
       " done relative. A fixed 80% threshold reports everybody on a site mid-migration and stays silent on a tidy one where a client missing a third of the time is remarkable."
      ]
     ]
    }
   ],
   "source": "docs/detection/correlation.md"
  },
  {
   "kind": "detector",
   "id": "path-campaign",
   "group": "Installed with site",
   "facts": [
    "ceiling moderate",
    "needs site"
   ],
   "summary": "A path the site never served that many unrelated clients suddenly want",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "b",
       "Reads: "
      ],
      [
       "t",
       "A path the site never served that many unrelated clients suddenly want"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "b",
       "With "
      ],
      [
       "code",
       "site"
      ],
      [
       "t",
       " — a warmed-up baseline of what the rest of your traffic looks like:"
      ]
     ]
    },
    {
     "kind": "h",
     "text": [
      [
       "t",
       "What each one is really for"
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "code",
       "path-campaign"
      ],
      [
       "t",
       " is its inverse, and catches what it misses. A freshly disclosed vulnerability looks like one URL nobody had ever requested being requested by hundreds of unrelated clients within the hour — each of them making a single request, which is nothing at all on its own. The miss rate is "
      ],
      [
       "b",
       "required"
      ],
      [
       "t",
       " rather than optional here, because many clients arriving at once on a brand-new URL is also exactly what a successful launch looks like. What separates them is whether the site had anything to serve."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "b",
       "The known cost of "
      ],
      [
       "code",
       "path-campaign"
      ],
      [
       "t",
       " is a broken link. Somebody shares a URL with a typo and thousands of real people follow it within the hour, which from the server is a path the site has never served, requested by many unrelated clients, answered "
      ],
      [
       "code",
       "not found"
      ],
      [
       "t",
       " every time — the firing shape exactly. Those people are reported at "
      ],
      [
       "code",
       "moderate"
      ],
      [
       "t",
       " and never refused; the corpus carries the case ("
      ],
      [
       "code",
       "broken-link-shared-widely"
      ],
      [
       "t",
       ") and holds it to the never-deny guarantee under every shipped preset."
      ]
     ]
    }
   ],
   "source": "docs/detection/correlation.md"
  },
  {
   "kind": "action",
   "id": "allow",
   "group": "Serves the request",
   "facts": [
    "not terminal",
    "costs a person nothing"
   ],
   "summary": "Serve it. Explicitly, and that is not the same as having no rule: an allow above your other rules is how you say \"this is fine, stop asking\".",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Serve it. Explicitly, and that is not the same as having no rule: an "
      ],
      [
       "code",
       "allow"
      ],
      [
       "t",
       " above your other rules is how you say \"this is fine, stop asking\"."
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "ts",
     "code": "{ id: \"verified-crawler-allow\", match: { verdict: \"verified-bot\" }, action: \"allow\",\n  reason: \"Crawler identity confirmed against its operator's DNS or published ranges.\" }"
    },
    {
     "kind": "p",
     "text": [
      [
       "code",
       "params.headers"
      ],
      [
       "t",
       " is honoured, so an allow can still carry something to the response."
      ]
     ]
    }
   ],
   "source": "docs/policy/actions.md"
  },
  {
   "kind": "action",
   "id": "log",
   "group": "Serves the request",
   "facts": [
    "not terminal",
    "costs a person nothing"
   ],
   "summary": "Serve it, and record it. The whole of monitor-only is built from this.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Serve it, and record it. The whole of "
      ],
      [
       "code",
       "monitor-only"
      ],
      [
       "t",
       " is built from this."
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "ts",
     "code": "{ id: \"observe-suspected\", match: { verdict: \"suspected-bot\" }, action: \"log\" }"
    }
   ],
   "source": "docs/policy/actions.md"
  },
  {
   "kind": "action",
   "id": "tag",
   "group": "Serves the request",
   "facts": [
    "not terminal",
    "costs a person nothing"
   ],
   "summary": "Serve it, and attach the verdict to the request so your own handlers can react without re-running detection: x-bot-verdict, x-bot-score, x-bot-class, x-bot-certain, x-bot-reason.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Serve it, and attach the verdict to the "
      ],
      [
       "b",
       "request"
      ],
      [
       "t",
       " so your own handlers can react without re-running detection: "
      ],
      [
       "code",
       "x-bot-verdict"
      ],
      [
       "t",
       ", "
      ],
      [
       "code",
       "x-bot-score"
      ],
      [
       "t",
       ", "
      ],
      [
       "code",
       "x-bot-class"
      ],
      [
       "t",
       ", "
      ],
      [
       "code",
       "x-bot-certain"
      ],
      [
       "t",
       ", "
      ],
      [
       "code",
       "x-bot-reason"
      ],
      [
       "t",
       "."
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "ts",
     "code": "app.get(\"/search\", (req, res) => {\n  const bot = req.headers[\"x-bot-verdict\"] !== \"unknown\";\n  res.json(bot ? cachedResults() : personalisedResults(req.user));\n});"
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Response-side verdict headers are "
      ],
      [
       "b",
       "off by default"
      ],
      [
       "t",
       " ("
      ],
      [
       "code",
       "exposeVerdictHeaders"
      ],
      [
       "t",
       "). An "
      ],
      [
       "code",
       "X-Bot-Score"
      ],
      [
       "t",
       " in the response is a live feedback signal for anyone tuning a scraper against you."
      ]
     ]
    }
   ],
   "source": "docs/policy/actions.md"
  },
  {
   "kind": "action",
   "id": "delay",
   "group": "Serves the request",
   "facts": [
    "not terminal",
    "costs a person a moment"
   ],
   "summary": "Serve it, slowly. params.delayMs, default 500 ms, capped at 10 s.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Serve it, slowly. "
      ],
      [
       "code",
       "params.delayMs"
      ],
      [
       "t",
       ", default 500 ms, capped at 10 s."
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "ts",
     "code": "{ id: \"slow-suspects\", match: { verdict: \"suspected-bot\" }, action: \"delay\",\n  params: { delayMs: 1500 } }"
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Cheap for you and expensive for anything making thousands of requests, while a person notices a pause and nothing else. It holds a connection open, so it is a poor choice under heavy concurrency — prefer "
      ],
      [
       "code",
       "rate-limit"
      ],
      [
       "t",
       " there."
      ]
     ]
    }
   ],
   "source": "docs/policy/actions.md"
  },
  {
   "kind": "action",
   "id": "rate-limit",
   "group": "Serves the request",
   "facts": [
    "not terminal",
    "costs a person a retry, if they are fast"
   ],
   "summary": "A fixed window per actor. Over the limit, the request is refused with 429 and a Retry-After.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "A fixed window per actor. Over the limit, the request is refused with "
      ],
      [
       "code",
       "429"
      ],
      [
       "t",
       " and a "
      ],
      [
       "code",
       "Retry-After"
      ],
      [
       "t",
       "."
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "ts",
     "code": "{ id: \"scraper-ratelimit\", match: { botClass: \"scraper\" }, action: \"rate-limit\",\n  params: { limit: { max: 60, windowMs: 60_000 } } }"
    },
    {
     "kind": "p",
     "text": [
      [
       "b",
       "This is the one action that needs a shared store."
      ],
      [
       "t",
       " A limit of 100/minute enforced independently by four replicas is a limit of 400/minute. With the default in-memory store it is per-instance, and the library will not pretend otherwise."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "A fixed window rather than a sliding one: one round trip instead of several, and the extra precision buys nothing for a mechanism whose job is to bound abuse rather than measure it."
      ]
     ]
    }
   ],
   "source": "docs/policy/actions.md"
  },
  {
   "kind": "action",
   "id": "challenge",
   "group": "Serves the request",
   "facts": [
    "not terminal",
    "costs a person seconds, and a working browser"
   ],
   "summary": "Serve a proof-of-work interstitial. Solving it grants a signed clearance cookie; the clearance detector reads it on subsequent requests.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Serve a proof-of-work interstitial. Solving it grants a signed clearance cookie; the "
      ],
      [
       "code",
       "clearance"
      ],
      [
       "t",
       " detector reads it on subsequent requests."
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "ts",
     "code": "{ id: \"suspected-challenge\", match: { verdict: \"suspected-bot\", minScore: 70 },\n  action: \"challenge\" }"
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Needs "
      ],
      [
       "code",
       "challenge.secrets"
      ],
      [
       "t",
       " configured — without it, a rule asking for one degrades to a "
      ],
      [
       "code",
       "tag"
      ],
      [
       "t",
       " and says so through "
      ],
      [
       "code",
       "onWarning"
      ],
      [
       "t",
       ". See the challenge for what it does and does not buy."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Challenging an actor that already holds valid clearance is refused and warned about: passing a challenge cannot change a proven verdict, so re-issuing would loop for ever."
      ]
     ]
    }
   ],
   "source": "docs/policy/actions.md"
  },
  {
   "kind": "action",
   "id": "custom",
   "group": "Serves the request",
   "facts": [
    "not terminal",
    "costs a person whatever you wrote"
   ],
   "summary": "Your own handler, registered by name.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Your own handler, registered by name."
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "ts",
     "code": "import { defineHandler } from \"@osqd/bothandlerjs\";\n\nconst shadowBan = defineHandler({\n  id: \"shadow-ban\",\n  description: \"Serves an empty result set rather than an error\",\n  execute: ({ assessment }) => ({\n    kind: \"respond\",\n    status: 200,\n    headers: { \"content-type\": \"application/json\" },\n    body: JSON.stringify({ results: [] }),\n  }),\n});\n\nnew BotHandler({\n  handlers: [shadowBan],\n  rules: [{ id: \"shadow\", match: { botClass: \"scraper\" }, action: \"custom\",\n            params: { handler: \"shadow-ban\" } }],\n});"
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "An "
      ],
      [
       "code",
       "execute"
      ],
      [
       "t",
       " returns one of three things: "
      ],
      [
       "code",
       "{ kind: \"continue\" }"
      ],
      [
       "t",
       " — optionally with "
      ],
      [
       "code",
       "requestHeaders"
      ],
      [
       "t",
       ", "
      ],
      [
       "code",
       "responseHeaders"
      ],
      [
       "t",
       " or a "
      ],
      [
       "code",
       "delayMs"
      ],
      [
       "t",
       " — "
      ],
      [
       "code",
       "{ kind: \"respond\", status, headers, body }"
      ],
      [
       "t",
       ", or "
      ],
      [
       "code",
       "{ kind: \"drop\" }"
      ],
      [
       "t",
       ". It may be async."
      ]
     ]
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "A handler named in a rule but not registered serves the request and warns. "
      ],
      [
       "b",
       "The guard does not apply to custom handlers"
      ],
      [
       "t",
       " — it cannot know what yours does — so a handler that denies service is a decision you own entirely."
      ]
     ]
    }
   ],
   "source": "docs/policy/actions.md"
  },
  {
   "kind": "action",
   "id": "redirect",
   "group": "Ends the request",
   "facts": [
    "terminal",
    "costs a person their destination"
   ],
   "summary": "Terminal. params.location is required; without it the request is served and a warning is raised.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Terminal. "
      ],
      [
       "code",
       "params.location"
      ],
      [
       "t",
       " is required; without it the request is served and a warning is raised."
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "ts",
     "code": "{ id: \"bots-to-api\", match: { certain: true, botClass: \"scraper\" }, action: \"redirect\",\n  params: { location: \"/api/docs\" } }"
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Useful for sending automation somewhere it can be served cheaply and correctly — a data endpoint, a sitemap, a licensing page — rather than simply refusing it."
      ]
     ]
    }
   ],
   "source": "docs/policy/actions.md"
  },
  {
   "kind": "action",
   "id": "block",
   "group": "Ends the request",
   "facts": [
    "terminal",
    "costs a person the page"
   ],
   "summary": "Terminal. 403 by default with a plain-text body; params.status and params.body override both.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Terminal. "
      ],
      [
       "code",
       "403"
      ],
      [
       "t",
       " by default with a plain-text body; "
      ],
      [
       "code",
       "params.status"
      ],
      [
       "t",
       " and "
      ],
      [
       "code",
       "params.body"
      ],
      [
       "t",
       " override both."
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "ts",
     "code": "{ id: \"scanner-block\", match: { botClass: \"scanner\", certain: true }, action: \"block\",\n  params: { status: 403, body: \"Automated scanning is not served here.\" },\n  reason: \"Proven scanner. Refused on proof, not on suspicion.\" }"
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "The body reaches a person often enough to be worth writing. Say what happened and how to reach you."
      ]
     ]
    }
   ],
   "source": "docs/policy/actions.md"
  },
  {
   "kind": "action",
   "id": "drop",
   "group": "Ends the request",
   "facts": [
    "terminal",
    "costs a person the page, with no explanation"
   ],
   "summary": "Terminal, and the harshest thing here: the connection is destroyed with no response at all. What a port behind a dropping firewall looks like.",
   "blocks": [
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Terminal, and the harshest thing here: the connection is destroyed with no response at all. What a port behind a dropping firewall looks like."
      ]
     ]
    },
    {
     "kind": "code",
     "lang": "ts",
     "code": "{ id: \"denylisted\", match: { detector: [\"ip-intelligence\"], certain: true }, action: \"drop\" }"
    },
    {
     "kind": "p",
     "text": [
      [
       "t",
       "Reserve it for traffic you have decided about — a denylist entry, a confirmed attack. A person who hits this gets a browser error with nothing in it, cannot tell your site from an outage, and has no way to contact you. "
      ],
      [
       "code",
       "block"
      ],
      [
       "t",
       " with a "
      ],
      [
       "code",
       "reason"
      ],
      [
       "t",
       " is almost always the better answer."
      ]
     ]
    }
   ],
   "source": "docs/policy/actions.md"
  }
 ]
};
