import { sendsModernHeaders } from "../internal/ua.js";
import { absenceIsMeaningful } from "./types.js";
import type { Detector, DetectionContext } from "./types.js";
import type { Evidence } from "../types.js";

/** First major version of each engine to ship Fetch Metadata by default. */
const FETCH_METADATA_SINCE: Record<string, number> = { blink: 76, gecko: 90 };

const VALID_SITE = new Set(["cross-site", "same-origin", "same-site", "none"]);
const VALID_MODE = new Set(["cors", "navigate", "no-cors", "same-origin", "websocket"]);

/**
 * Checks the Fetch Metadata headers (`Sec-Fetch-Site`, `-Mode`, `-Dest`, `-User`).
 *
 * These are *forbidden* headers: page JavaScript cannot set or alter them, so in a
 * real browser they are generated by the network stack from the actual context of
 * the request. That makes them unusually hard to fake convincingly — a client
 * assembling requests by hand either omits them or picks a combination the browser
 * would never produce.
 *
 * Two failure modes are checked. **Absence** on an engine known to send them, over
 * HTTPS, where they should be present. And **incoherence** — a `Sec-Fetch-Dest:
 * document` that is not a navigation describes a request no browser makes.
 *
 * Neither is `certain`, for the same reason as elsewhere: a stripping proxy in front
 * of your server produces the first, and an unusual-but-real client integration can
 * produce the second. Together with a matching header set, though, they are among
 * the sharpest probabilistic signals available.
 */
export function fetchMetadataDetector(): Detector {
  return {
    id: "fetch-metadata",
    description: "Checks Sec-Fetch-* headers for absence on engines that send them, and for internally incoherent combinations",
    cost: "cheap",
    stage: "always",

    inspect(ctx: DetectionContext): Evidence[] | undefined {
      const { headers, protocol } = ctx.facts;
      const site = headers["sec-fetch-site"];
      const mode = headers["sec-fetch-mode"];
      const dest = headers["sec-fetch-dest"];
      const results: Evidence[] = [];

      if (site === undefined && mode === undefined && dest === undefined) {
        if (!absenceIsMeaningful(ctx)) return undefined;
        // A Chromium fork or an embedded build cannot be assumed to send these.
        if (!sendsModernHeaders(ctx.ua)) return undefined;
        // Only Safari's older releases are exempt, and we cannot reliably date a
        // Safari build from its UA, so we check only Blink and Gecko.
        const since = ctx.ua.engine !== undefined ? FETCH_METADATA_SINCE[ctx.ua.engine] : undefined;
        if (since !== undefined && protocol === "https" && (ctx.ua.majorVersion ?? 0) >= since) {
          results.push({
            detector: "fetch-metadata",
            summary: `User-Agent claims ${ctx.ua.browser} ${ctx.ua.majorVersion} over HTTPS but sent no Sec-Fetch-* headers`,
            direction: "bot",
            certainty: "strong",
            weight: 0.6,
            botClass: "impersonator",
            family: "stripped-headers",
            metadata: { engine: ctx.ua.engine, majorVersion: ctx.ua.majorVersion },
          });
        }
        return results.length > 0 ? results : undefined;
      }

      // A document destination is, by definition, a navigation. Anything else is a
      // combination the browser's own network stack would not assemble.
      if (dest === "document" && mode !== undefined && mode !== "navigate") {
        results.push({
          detector: "fetch-metadata",
          summary: `Incoherent Fetch Metadata: Sec-Fetch-Dest is "document" but Sec-Fetch-Mode is "${mode}"`,
          direction: "bot",
          certainty: "strong",
          weight: 0.7,
          botClass: "impersonator",
          metadata: { dest, mode, site },
        });
      }

      // `Sec-Fetch-User: ?1` marks a navigation the *user* initiated. It is only ever
      // sent on navigations, and its only legal value is `?1`.
      //
      // The mode half is checked only when a mode was actually received — the same
      // guard the destination check above uses, and it was missing here. Written as
      // `mode !== "navigate"` it also fired when the header was simply not in front of
      // us: a real Chrome navigation replayed from a log that recorded Sec-Fetch-User
      // but not Sec-Fetch-Mode was accused on the strength of an absence, with the
      // `?1` it did send being exactly right.
      const user = headers["sec-fetch-user"];
      if (user !== undefined && (user.trim() !== "?1" || (mode !== undefined && mode !== "navigate"))) {
        results.push({
          detector: "fetch-metadata",
          summary: `Sec-Fetch-User sent as "${user.slice(0, 16)}" with mode "${mode ?? "absent"}"; browsers send it only as ?1 on user-initiated navigations`,
          direction: "bot",
          certainty: "moderate",
          botClass: "impersonator",
          metadata: { user: user.slice(0, 16), mode },
        });
      }

      for (const [name, value, allowed] of [
        ["sec-fetch-site", site, VALID_SITE],
        ["sec-fetch-mode", mode, VALID_MODE],
      ] as const) {
        if (value !== undefined && !allowed.has(value.trim().toLowerCase())) {
          results.push({
            detector: "fetch-metadata",
            summary: `${name} has the non-standard value "${value.slice(0, 32)}"`,
            direction: "bot",
            certainty: "moderate",
            botClass: "impersonator",
            metadata: { header: name, value: value.slice(0, 32) },
          });
        }
      }

      return results.length > 0 ? results : undefined;
    },
  };
}
