/**
 * Bundles the dashboard's browser code into the string `page.ts` serves.
 *
 * Why there is a build step at all: the client used to live inside a
 * `String.raw` template in `page.ts` — two thousand lines of JavaScript that
 * TypeScript never looked at, Biome never linted (it globs `*.ts`, and this was a
 * string) and no test could import a function out of. That is how a call to a
 * function nobody had written shipped: `drawAudit()` threw a `ReferenceError` on
 * every render of the Statistics tab, blanking every panel below it, and nothing in
 * the toolchain was in a position to notice. It is a real module now, and this turns
 * it back into the one thing a bundled library can rely on being able to serve — a
 * string it carries itself.
 *
 * The output is committed. A fresh checkout has to be able to run `tsx demo/server.ts`
 * without a generate step first, and `prebuild` / `pretest` / `pretypecheck` regenerate
 * it, so the committed copy cannot drift for long. `npm run client:check` fails if it
 * has.
 */
import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const target = join(root, "src", "dashboard", "client.generated.ts");

/**
 * Sequences that would end the `<script>` element early, or open a comment the HTML
 * parser reads before the JavaScript one does.
 *
 * An HTML parser stops a script at the first `</script` in the *source*, including one
 * inside a string literal. Nothing in the client writes those today; this is here so
 * that the day somebody adds one it fails in CI rather than in an operator's browser.
 */
const FORBIDDEN_IN_SCRIPT = ["</script", "<!--", "-->"];

/**
 * Ways to put attacker-written text into a document as markup.
 *
 * Every value on this page — User-Agents, paths, evidence summaries — is written by
 * the client being assessed. `tests/dashboard.test.ts` asserts the served page
 * contains none of these; catching it here names the file instead of the byte offset.
 */
const FORBIDDEN_SINKS = ["innerHTML", "outerHTML", "insertAdjacentHTML", "document.write"];

export async function buildClient() {
  const result = await build({
    entryPoints: [join(root, "src", "dashboard", "client", "index.ts")],
    bundle: true,
    format: "iife",
    // Not minified on purpose. This is an operator's tool served from loopback, where
    // a hundred kilobytes costs nothing and being able to read the running page in
    // devtools costs nothing either.
    minify: false,
    target: ["es2020"],
    legalComments: "none",
    charset: "utf8",
    write: false,
    logLevel: "silent",
  });

  const code = result.outputFiles[0].text;

  for (const sequence of FORBIDDEN_IN_SCRIPT) {
    if (code.includes(sequence)) throw new Error(`The dashboard client bundle contains ${JSON.stringify(sequence)}, which would end its <script> element early.`);
  }
  for (const sink of FORBIDDEN_SINKS) {
    if (code.includes(sink)) throw new Error(`The dashboard client bundle contains ${sink}. Every value on that page is client-written text and reaches the document through textContent.`);
  }

  return `/**
 * Generated by \`npm run client:build\` from \`src/dashboard/client/\`. Do not edit.
 *
 * The dashboard's browser code, bundled into the string \`page.ts\` stamps into its
 * one nonced <script>. See scripts/build-client.mjs for why this exists.
 */

/* eslint-disable */
export const CLIENT_SCRIPT = ${JSON.stringify(code)};
`;
}

/**
 * The package's own version, as a constant the source can import.
 *
 * Generated here rather than read from `package.json` at runtime because this library
 * ships as both ESM and CJS and is bundled into other people's builds: `import.meta.url`
 * and `require("../package.json")` each work in about half of those places, and the half
 * they fail in is somebody else's application.
 *
 * What it is for is the dashboard telling an embedded `<bot-dashboard>` what it is
 * talking to. The element is a *separate* bundle in the host page's build, so the two
 * can be different versions — and the symptom of that is a screen that is subtly wrong
 * rather than an error, which is the worst kind of thing to debug by eye.
 */
const versionTarget = join(root, "src", "version.generated.ts");

async function buildVersion() {
  const { version } = JSON.parse(await readFile(join(root, "package.json"), "utf8"));
  return `/**
 * Generated by \`npm run client:build\` from \`package.json\`. Do not edit.
 *
 * See scripts/build-client.mjs for why this is generated rather than read at runtime.
 */

/* eslint-disable */
export const VERSION = ${JSON.stringify(version)};
`;
}

const outputs = [
  [target, await buildClient(), "dashboard client bundle", "src/dashboard/client.generated.ts"],
  [versionTarget, await buildVersion(), "version constant", "src/version.generated.ts"],
];

for (const [file, contents, label, name] of outputs) {
  const existing = await readFile(file, "utf8").catch(() => "");
  if (process.argv.includes("--check")) {
    if (existing !== contents) {
      console.error(`${name} is out of date. Run \`npm run client:build\`.`);
      process.exit(1);
    }
    console.log(`${label} is up to date`);
  } else if (existing === contents) {
    console.log(`${label} unchanged`);
  } else {
    await writeFile(file, contents);
    console.log(`${label} written (${(contents.length / 1024).toFixed(1)} kB)`);
  }
}
