/**
 * Generated by `npm run client:build` from `package.json`. Do not edit.
 *
 * See scripts/build-client.mjs for why this is generated rather than read at runtime.
 */

/* eslint-disable */
export const VERSION = "0.9.2";
